django_world/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^TER/', include('hello_world.urls', namespace='hello_world')),  # this line added
    url(r'^admin/', admin.site.urls),
]

hello_world/urls.py
from django.conf.urls import url
from . import views

app_name = "hello_world"

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
    url(r'^[Ii]ntroduction/?$', views.introduction.as_view(), name="Introduction"),
    url(r'^[Cc]oncepts?/?$', views.concepts.as_view(), name="Concepts"),
    url(r'^[Ff]inance/?$', views.finance.as_view(), name="Finance"),
    url(r'^[Aa]pplication/?$', views.ApplicationsView.as_view(), name="Application"),
    url(r'^[Cc]onclusion/?$', views.conclusion.as_view(), name="Conclusion"),
    url(r'^test$', views.test.as_view(), name="Test"),
]

hello_world/models.py
from django.db import models
import datetime
from django.utils import timezone


# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.


class HistoricIndexes(models.Model):
    id = models.IntegerField(db_column='Id', primary_key=True, blank=True)
    datetime = models.DateTimeField(db_column='DateTime', blank=True, null=True)
    nasqad = models.DecimalField(db_column='Nasdaq', max_digits=20, decimal_places=19)
    dowjones = models.DecimalField(db_column='Dowjones', max_digits=20, decimal_places=19)
    snp500 = models.DecimalField(db_column='SnP500', max_digits=20, decimal_places=19)
    rates = models.DecimalField(db_column='Rates', max_digits=20, decimal_places=19)

    class Meta:
        db_table = 'historic_indexes'


class PredictedIndexes(models.Model):
    id = models.IntegerField(db_column='Id', primary_key=True, blank=True)
    label = models.CharField(db_column="Label", max_length=20)
    datetime = models.DateTimeField(db_column='DateTime')
    nasqad = models.DecimalField(db_column='Nasdaq', max_digits=20, decimal_places=19)
    dowjones = models.DecimalField(db_column='Dowjones', max_digits=20, decimal_places=19)
    snp500 = models.DecimalField(db_column='SnP500', max_digits=20, decimal_places=19)
    rates = models.DecimalField(db_column='Rates', max_digits=20, decimal_places=19)

    class Meta:
        db_table = 'predicted_indexes'

class Snp500(models.Model):
    id = models.IntegerField(db_column='Id', primary_key=True, blank=True)
    datetime = models.DateTimeField(db_column='DateTime')
    closing = models.DecimalField(db_column='Closing', max_digits=30, decimal_places=25)

    class Meta:
        db_table = 'snp500'

hello_world/views.py
# Django
from django.views import generic
from hello_world.models import HistoricIndexes
from django.shortcuts import render

# Bokeh
from bokeh.plotting import figure
from bokeh.embed import components
from hello_world.Scripts import plotting


def MetaChapter(file):
    class Chapter(generic.base.TemplateView):
        template_name = 'hello_world/' + file + '.html'

    return Chapter


class ApplicationsView(generic.base.TemplateView):
    template_name = 'hello_world/application.html'
    context_object_name = 'context'

    def get_context_data(self, *args, **kwargs):
        context = super(ApplicationsView, self).get_context_data(**kwargs)

        indexes = "Rates DowJones Nasdaq SnP500".split()
        context['indexes'] = indexes

        ffp, ffe, ffn = plotting.plot_feedforward('1')

        lstmp, lstme = plotting.plot_lmst()

        ffp_script, ffp_divs = components(ffp)
        ffe_script, ffe_divs = components(ffe)
        ffn_script, ffn_divs = components(ffn)

        lstmp_script, lstmp_divs = components(lstmp)
        lstme_script, lstme_divs = components(lstme)

        context['plot'] = {
            'lstm': lstmp_divs
        }
        context['error'] = {
            'lstm': lstme_divs
        }
        context['normalised'] = {}
        context['script'] = '\n'.join([lstmp_script, lstme_script])
        for index in indexes:
            context['plot'][index] = ffp_divs[index]
            context['error'][index] = ffe_divs[index]
            context['normalised'][index] = ffn_divs[index]
        context['script'] += '\n' + '\n'.join([ffp_script, ffe_script, ffn_script])
        return context


introduction = MetaChapter('introduction')
concepts = MetaChapter('concepts')
finance = MetaChapter('finance')
application = MetaChapter('application')
conclusion = MetaChapter('conclusion')
test = MetaChapter('test')
index = MetaChapter('index')

hello_world/templates/hello_world/Chapter1.html
{% extends 'hello_world/base.html' %}
{% load extras %}
{% load staticfiles %}

{% block title %}
    <title>TER Version 2!</title>
{% endblock %}

{% block content %}
    <p> Hello World !! </p>
{% endblock %}

hello_world/templates/hello_world/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    {% block title %}{% endblock %}

    {# Bokeh style #}
    <link rel="stylesheet" href="http://cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/reset.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/site.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/container.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/grid.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/header.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/image.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/menu.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/divider.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/list.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/segment.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/dropdown.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/icon.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/sticky.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/Semantic-UI/components/tab.min.css' %}">

    {# Notre feuille de style #}
    <link rel="stylesheet" type="text/css" href="{% static 'hello_world/style.css' %}">

    <script src="{% static 'hello_world/Semantic-UI/jquery.min.js' %}"></script>
    <script src="{% static 'hello_world/Semantic-UI/components/dropdown.min.js' %}"></script>
    <script src="{% static 'hello_world/Semantic-UI/components/visibility.min.js' %}"></script>
    <script src="{% static 'hello_world/Semantic-UI/components/sticky.min.js' %}"></script>
    <script src="{% static 'hello_world/Semantic-UI/components/tab.min.js' %}"></script>

    {# Latex equations #}
    <link rel="stylesheet" href="{% static 'hello_world/jqmath.css' %}">
    <script src="{% static 'hello_world/jqmath-etc-0.4.6.min.js' %}" charset="utf-8"></script>

    {# Bokeh script #}
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js"></script>

    {# Google code prettyfier #}
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>

    {# Nos scripts #}
    <script src="{% static 'hello_world/myscript.js' %}"></script>

</head>

<header>
    <div style="margin-top: 1ex;">
        <img class="image center main" align="center" src="{% static 'hello_world/images/banner.svg' %}">
    </div>
    <div class="ui borderless main menu top" id="menu" style="background: lightsteelblue;">
        <div class="ui text container">
            <div id="titre_menu" class="header item left">
                <img class="logo" src="{% static 'hello_world/images/icon.png' %}">
            </div>
            <div class="header item left">
                <a href="{% url 'hello_world:index' %}" id="titre_menu">
                    Prédiction des dynamiques financières
                </a>
            </div>
            <div class="ui dropdown simple item">
                Naviguer <i class="dropdown icon"></i>
                <div class="ui menu">
                    <a class="item" href="{% url 'hello_world:Introduction' %}/#menu">
                        <img src="{% static 'hello_world/images/icon.png' %}">
                        Introduction générale
                    </a>
                    <a class="item" href="{% url 'hello_world:Concepts' %}/#menu">
                        <img src="{% static 'hello_world/images/introduction_icon.png' %}">
                        Introduction aux réseaux de neurones
                    </a>
                    <a class="item" href="{% url 'hello_world:Finance' %}/#menu">
                        <img src="{% static 'hello_world/images/finance_icon.png' %}">
                        Etat de l'art dans la Finance
                    </a>
                    <a class="item" href="{% url 'hello_world:Application' %}/#menu">
                        <img src="{% static 'hello_world/images/application_icon.png' %}">
                        Applications Pratiques
                    </a>
                    <a class="item" href="{% url 'hello_world:Conclusion' %}/#menu">
                        <img src="{% static 'hello_world/images/feather.png' %}">
                        Conclusion générale
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

<body>

{#<div class="overlay">#}
{#    <div class="ui vertical menu" style="width:64px;">#}
{#        <a href="{% url 'hello_world:Introduction' %}/#menu" class="item icon image center"><img src="{% static 'hello_world/images/icon.png' %}"></a>#}
{#        <a href="{% url 'hello_world:Concepts' %}/#menu" class="item icon image center"><img src="{% static 'hello_world/images/introduction_icon.png' %}"></a>#}
{#        <a href="{% url 'hello_world:Finance' %}/#menu" class="item icon image center"><img src="{% static 'hello_world/images/finance_icon.png' %}"></a>#}
{#        <a href="{% url 'hello_world:Application' %}/#menu" class="item icon image center"><img src="{% static 'hello_world/images/application_icon.png' %}"></a>#}
{#        <a href="{% url 'hello_world:Conclusion' %}/#menu" class="item icon image center"><img src="{% static 'hello_world/images/feather.png' %}"></a>#}
{#    </div>#}
{#</div>#}

{% block content %}{% endblock %}

<footer>
    <div class="ui segment footer" style="background-color: steelblue;">
        <div style="margin-top: -3em;margin-bottom: -3em;" class="ui center aligned container">
            <div class="ui divided grid">
                <div class="five wide column">
                    <h4 class="ui inverted header center aligned">Travaux d'Etudes et de Recherches</h4>
                </div>
                <div class="five wide column">
                    <h4 class="ui inverted header center aligned">Licence 3 parcours mixtes</h4>
                </div>
                <div class="five wide column">
                    <h4 class="ui inverted header center aligned">
                        <a style="color:white;"
                           href="http://math-interactions.u-bordeaux.fr/Formations/Licence-MIASHS/Informations">
                            Université de Bordeaux
                        </a>
                        <img style="margin-left:2ex;" src="{% static 'hello_world/images/univ.png' %}">
                    </h4>
                </div>
            </div>
            <div class="ui section divider"></div>
            <div class="ui horizontal inverted small divided list">
                <a class="item" href="#">Kalla Mohammad</a>
                <a class="item" href="#">Lassourreuille Simon</a>
                <a class="item" href="#">Seze Thomas</a>
            </div>
        </div>
    </div>

</footer>

<script src="{% static 'hello_world/myscriptslate.js' %}"></script>

</body>

</html>

hello_world/templates/hello_world/conclusion.html
{% extends 'hello_world/base.html' %}
{% load extras %}
{% load staticfiles %}

{% block title %}
    <title>TER !</title>
{% endblock %}

{% block content %}

    <div class="main ui container">
        <div class="chapter content" id="chapter1">

            <h1 class="chapter header">
                Conclusion générale
            </h1>

            <div class="ui segment raised">
                <p>
                    Rappelons que la problématique était la suivante : "Peut-on prévoir efficacement les dynamiques
                    financières à l'aide des réseaux de neurones artificiels?". Nous avons donc décidé, à la façon de
                    Machiavel <span class="citation">"Divide et impera"</span>, de diviser le problème en sous problème
                    afin de le résoudre de façon plus fluide et pertinente.
                </p>
                <p>
                    Dans la première partie, nous avons appris, suite à l'étude de plusieurs articles financiers, que
                    l'analyse d'un indice boursier était extrêmement complexe. En effet, leur évolution seraient à la
                    fois lié à l'état des finances réelles, mais aussi à la psychologie des investisseurs.
                </p>
                <p>
                    Dans la seconde partie, nous nous sommes appropriés les bases tant théoriques que pratiques des
                    réseaux
                    de neurones artificiels. Après avoir implémenté nos réseaux de neurones, et amélioré ceux-ci à
                    l'aide d'un savoir empirique, nous avons pu comparer les résultats prédits finaux par nos différents réseaux
                    avec les valeurs réelles de l'indice boursier.
                </p>
                <p>
                    De ces résultats, nous avons conclu que notre meilleur réseau était le Feed Forward programmé en
                    python. En effet, pour 3 indices boursiers, les données qu'il a prédites présentent au plus 1% d'écart avec
                    les données réelles. Néanmoins, ce réseau n'est efficace qu'à court terme, se basant sur les 10 derniers
                    jours passés pour prédire le cours de l'indice.
                </p>
                <p>
                    Une des raison qui pourrait expliquer le manque de performance de notre réseau à long terme est le
                    fait qu'il ne se base que sur des variables quantitatives. En effet, nous nous basons uniquement sur des
                    données historiques, qui ne permettent pas à elles seules d'expliquer les variations des indices
                    boursiers.
                    En effet, elles ne se limitent qu'à l'aspect quantitatif de l'indice boursier, sans prendre en
                    compte
                    les multiples variables qualitatives qui l'influencent. Pour améliorer les performances de notre
                    réseau
                    de neurones artificiels, il serait intéressant de lui fournir d'autre données en entrées, capable de
                    modéliser l'état de santé des entreprises (bilan financier, stratégies adoptées) et la psychologique des
                    investisseurs. Les nouvelles impactant fortement la psychologie de ces derniers, il serait surement
                    intéressant de développer un second réseau de neurones, dont le but serait d'analyser les nouvelles
                    liées
                    à un indice, et d'en déterminer l'avis général (positif ou négatif). Les données de ce second réseau
                    seraient envoyées en entrée du premier, permettant ainsi d'avoir un modèle se basant à la fois sur
                    l'état de santé de l'indice et sur la psychologie des investisseurs, améliorant ainsi théoriquement
                    les prédictions du modèle. Cette théorie a été vérifiée par les performances du fond
                    d'investissement
                    Medaillon, qui se base sur la prédiction d'évolution d'indices boursiers, en utilisant des centaines
                    de variables explicatives dans leur modèle, ce qui leur confère le statut de "fond d'investissement
                    le
                    plus performant de l'histoire".
                </p>
            </div>
            <h1 class="chapter header">
                Bibliographie
            </h1>
            <div class="ui segment raised">
            <ol>
                <li>
                    Martin P. Wallace (PhD),<a href="http://www.saycocorporativo.com/saycouk/bij/journal/vol1no1/article_3.pdf"> Neural Networks and their application to finance</a>, 2008
                </li>
                <li>
                    Adam Fadlalla, Chien-Hua Lin, <a href="http://cns-classes.bu.edu/cn710/Fall2007/file_repository/112.pdf"> An analysis of the applications of neural networks in finance</a>, 2001
                </li>
                <li>
                    Philippe Paquet,<a href="http://grorichome.dyndns.org/oldsite/groricorssgoo/web/pdf/1997-1.pdf"> L'utilisation des réseaux de neurones artficiels en finance</a>, 1997
                </li>
                <li>
                    Christian L. Dunis, Jason Laws, Andreas Karathanasopoulos, <a href="https://link-springer-com.docelec.u-bordeaux.fr/book/10.1007/978-1-4614-3773-4">Financial decision making using computational intelligence : Chapter 4 Modelling and Trading the Greek Stock Market with Hybrid ARMA-Neural Network Models </a>, edition Springer, 2012
                </li>
                <li>
                    Jakob Aungiers, <a href="http://www.jakob-aungiers.com/articles/a/LSTM-Neural-Network-for-Time-Series-Prediction"> LSTM neural network for time series prediction</a>, 2016
                </li>
            </ol>
            </div>
            {#            {% for index in divs %}#}
            {#                <div class="ui segment raised">#}
            {#                    <h3 class="header" align="center">{{ index }}</h3>#}
            {#                    {{ divs|key:index|safe }}#}
            {#                </div>#}
            {#            {% endfor %}#}
        </div>
    </div>
    {#    {{ script_bokeh|safe }}#}
{% endblock %}

hello_world/templates/hello_world/index.html
{% extends 'hello_world/base.html' %}
{% load extras %}
{% load staticfiles %}

{% block title %}
    <title>TER !</title>
{% endblock %}

{% block content %}

    <div class="main ui container">
        <div class="chapter content" id="chapter1">

            <div class="ui pointing secondary abstract menu floating right">
                <div class="right menu">
                    <a class="active blue item" data-tab="english">English</a>
                    <a class="blue item" data-tab="french">French</a>
                </div>
            </div>

            <div class="ui active tab segment" data-tab="english">
                <h3>Abstract : </h3>
                <p>
                    Many economists and traders agree to say that the market is unstable and its variations are random,
                    making them difficult to predict. However, some banks or hedge funds have developed algorithms that
                    allow them to predict the market variation well enough to get profit out of it.
                    The purpose of this project was to determinate if it was possible to predict the financial
                    market variations using artificial neural networks.
                    To achieve this goal, we used a model of artificial neural network to generate predicted values,
                    which we then compared to real values of financial products.
                    We found out that the predictions can give us relevant information about the short term future.
                    Furthermore,
                    these results suggest that we can predict at least the direction in which the financial products
                    are going to vary.
                    However, these predictions are not completely reliable and must be considered with caution, unlike
                    some other statistical models. <br/>
                </p>
            </div>
            <div class="ui tab segment" data-tab="french">
                <h3>Abstract : </h3>

                <p>
                    Beaucoup d'économistes et de traders s'accordent à dire que le marché financier est instable et que
                    ses variations sont aléatoires. De plus, même en considérant que de telles prédictions soient
                    possibles,
                    il serait trop complexe de les prédire à cause du nombre de variables conséquent devant être pris en
                    compte.
                    Pourtant, certaines banques ou fonds d'investissement ont développé des algorithmes leur permettant
                    de prédire les variations du marché financier de façon assez satisfaisante pour obtenir un bon
                    retour sur investissement.
                    Le but de ce projet était de déterminer s'il était possible de prédire l'évolution des variations du
                    marché financier
                    en utilisant des réseaux de neurones artificiels. Pour atteindre cet objectif, nous avons utilisé
                    plusieurs types de
                    réseaux de neurones artificiels pour générer des prédictions que nous avons ensuite comparées aux
                    valeurs réelles de 4 produits financiers .
                    Nous avons trouvé qu'à court terme il était possible d'approximer les cours réels par les
                    prédictions établies par
                    nos réseaux de neurones artificiels. Cependant, ils perdent rapidement leur pouvoir prédictif sur le
                    long terme, contrairement à
                    d'autres modèles statistiques classiques.
                </p>
            </div>


            <div class="ui segment raised">
                <h3>Plan du site :</h3>
                <ul>
                    <li><a href="{% url 'hello_world:Introduction' %}">Introduction générale : </a>
                        <ul>
                            <li><a href="{% url 'hello_world:Introduction' %}/#lapb">Problématique </a></li>
                            <li><a href="{% url 'hello_world:Introduction' %}/#ldf">Les dynamiques financières</a></li>
                            <li><a href="{% url 'hello_world:Introduction' %}/#lrdna">Les réseaux de neurones
                                artificiels</a></li>
                            <li><a href="{% url 'hello_world:Introduction' %}/#lrdnaaalf">Les réseaux de neurones
                                articiciels appliqués à la finance</a></li>
                            <li><a href="{% url 'hello_world:Introduction' %}/#lsdd">La selection des données</a></li>
                            <li><a href="{% url 'hello_world:Introduction' %}/#lm">La méthodologie</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'hello_world:Concepts' %}">Introduction aux réseaux de neurones : </a>
                        <ul>
                            <li><a href="{% url 'hello_world:Concepts' %}/#g">Généralité</a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#qdc">Dates clefs</a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#tddin"> Transition des données
                                inter-neurones </a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#lfa">Les fonctions d'activation</a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#l">L'apprentissage</a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#ldtdrdna">Les différents types de réseaux de
                                neurones artificiels</a></li>
                            <li><a href="{% url 'hello_world:Concepts' %}/#lldrdn">Les limites des réseaux de neurones
                                artificiels</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'hello_world:Finance' %}">Etat de l'art dans la finance :</a>
                        <ul>
                            <li><a href="{% url 'hello_world:Finance' %}/#intro">Introduction</a></li>
                            <li><a href="{% url 'hello_world:Finance' %}/#adrdnauef">Architecture des réseaux de
                                neurones artificiels utilisés en finance</a></li>
                            <li><a href="{% url 'hello_world:Finance' %}/#aef">Application en finance</a></li>
                            <li><a href="{% url 'hello_world:Finance' %}/#leslim">Les limites des réseaux de neurones
                                artificiels utilisés en finance</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'hello_world:Application' %}">Application pratique : </a>
                        <ul>
                            <li><a href="{% url 'hello_world:Application' %}/#app_intro">Introduction</a></li>
                            <li><a href="{% url 'hello_world:Application' %}/#strat">Stratégie empirique</a></li>
                            <li><a href="{% url 'hello_world:Application' %}/#rslt">Résultats obtenus</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url 'hello_world:Conclusion' %}">Conclusion</a></li>
                </ul>

            </div>

            <p>
                Petite note : la page des applications contient des graphes assez lourds à charger, ne vous inquiètez
                pas si le chargement est lent.
            </p>
        </div>
    </div>
{% endblock %}